### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by dennyverbeeck**
Key features now include:
- Creation of projects, subjects, devices, etc.
- Updated authentication/authorization and permissions systems
- Source assigner for assigning sources to subjects
- Ability to pair mobile apps to subjects by scanning a QR code from the app
- Updated project view
- Demo data no longer loaded when production profile is selected
- Fix issue that prevents new users from setting up a password
- Fix CORS issue on production profile
- Fix existing browser-based e2e tests
- Add new browser-based e2e tests
- `radar-auth`: Java library for authenticating clients that have tokens issued by ManagementPortal
- `oauth-client-util`: Java library for managing OAuth tokens in a client application using the client credentials grant type

### CODE REVIEW

**Comment by nivemaham** [comment]
Should we wait till we fix #105 and #92 before we make a major release?

**Comment by dennyverbeeck** [comment]
This is still a minor release, i think it's beneficial to release more often. I've also already set up an automated Docker build. There are a number of critical fixes in this branch already like the reset password bug and enabling CORS, needed for the development of the aRMT app. Let's release this as soon as possible so other developers can also continue their work, and include the fixes we're currently working on in a next minor or patch release?

**Comment by yatharthranjan** [comment]
@dennyverbeeck agreed. Also we need the new version to be released for starting the enrolment process.

**Comment by dennyverbeeck** [comment]
As per offline discussion, will go ahead with the merge and release.

**Pull request merged**
